### ISSUE TITLE
Paths logged in TransferLog by mod_sftp are different when mod_vroot is enabled

### ISSUE THREAD

**Issue by ws0w** [Castaglia/proftpd-mod_vroot#16]
When mod_vroot is enabled for a session, the paths of files uploaded/downloaded that are logged by mod_sftp to a TransferLog file are different than when mod_vroot is not used for a session.

For transparency/consistency, the TransferLog entries generated for a file upload/download should be the same regardless of whether mod_vroot is used for that transfer or not, and whether mod_sftp is used or not.

**Comment by Castaglia** [comment]
Is this similar to (_but different from_) Issue #2?

**Comment by ws0w** [comment]
Yes, it’s very similar. The difference is that it is specific to sftp ( and I assume scp) transfers. If I turn off the Vroot engine, the full path is logged. The full path is logged for ftps transfers regardless whether the vroot engine is on or off.  At first I thought it was specific to proftpd 1.3.6, but have the same behavior on proftpd 1.3.5b. Mod_vroot is version 0.9.5

**Comment by Castaglia** [comment]
Ah, I see.  The fix for Issue #2 does not work for `mod_sftp`, since it does not use/dispatch a `CMD` handler for those internal `RETR` FTP-like commands for SFTP/SCP sessions.  I'll see if I can patch in similar functionality into `mod_sftp`.

**Comment by ws0w** [comment]
Thanks.

**Comment by Castaglia** [comment]
This should be addressed in `mod_sftp` via [this PR](https://github.com/proftpd/proftpd/pull/623).

**Comment by Castaglia** [comment]
This has been fixed in the master proftpd branch (_i.e._ it's a `mod_sftp` fix, not a `mod_vroot` fix).

**Comment by ws0w** [comment]
I've verified that the fix was successful in my environment. Thanks.
