### ISSUE TITLE
Compilation Error with proftpd 1.3.6

### ISSUE THREAD

**Issue by osfrance** [Castaglia/proftpd-mod_vroot#18]
Hi,
I try to compile mod_vroot for using it with md_exec, but when I try to compile proftpd-1.3.6 with mod_vroot sources in contrib/ I had this error : 
### mod_vroot.c:34:19: fatal error: alias.h: No such file or directory
 #include "alias.h"
I also try to add include option in ./configure like this : --with-includes=/tmp/proftpd-1.3.6/contrib/ but I had a lot of errors : 
### mod_vroot.c: In function 'vroot_pre_pass':
mod_vroot.c:363:14: error: 'vroot_fsio_stat' undeclared (first use in this function)
   fs->stat = vroot_fsio_stat;
              ^
mod_vroot.c:363:14: note: each undeclared identifier is reported only once for each function it appears in
mod_vroot.c:364:15: error: 'vroot_fsio_lstat' undeclared (first use in this function)
   fs->lstat = vroot_fsio_lstat;
               ^
mod_vroot.c:365:16: error: 'vroot_fsio_rename' undeclared (first use in this function)
   fs->rename = vroot_fsio_rename;

Thanks for help, I need to use your module with mod_exec for production FTP in my Company.

**Comment by pghmcfc** [comment]
The way I build it is as follows:
* Untar the `mod_vroot` `v0.9.5.tar.gz` tarball in the proftpd `contrib/` directory
* Rename the resulting `proftpd-mod_vroot-0.9.5` directory to `mod_vroot`
* In the top-level proftpd directory, call `configure` with`mod_vroot` listed as one of the modules in either `--with-modules` or `--with-shared` (I use `--with-shared`)

That works for me.
