### ISSUE TITLE
Trying to compile mod_vroot for 1.3.5e

### ISSUE THREAD

**Issue by muzetik** [Castaglia/proftpd-mod_vroot#19]
Hi,

since a bug in 3.6 makes it impossible to transfer big files (connexion reset), I am trying to compile latest mod_vroot for 3.5, which is impossible since it is only compatible with 3.6

any solution ?

**Comment by muzetik** [comment]
any available version of mod_vroot for proftpd 1.3.5e ?

**Comment by pghmcfc** [comment]
In Fedora we used v0.9.4 with proftpd 1.3.5e:
https://github.com/Castaglia/proftpd-mod_vroot/archive/v0.9.4.tar.gz

**Comment by muzetik** [comment]
thanks, it can only be build as a dso module ?

**Comment by pghmcfc** [comment]
The documentation says you can build it static or as a DSO:
https://htmlpreview.github.io/?https://github.com/Castaglia/proftpd-mod_vroot/blob/master/mod_vroot.html#Installation

**Comment by Castaglia** [comment]
What was the build issue you were encountering?  With the releases of ProFTPD 1.3.6c, 1.3.7rc3, this shouldn't be an issue any longer, correct?

**Comment by Castaglia** [comment]
Closing stale ticket, due to lack of additional contact with reporter.
