### ISSUE TITLE
Paths logged in TransferLog are different when mod_vroot is enabled

### ISSUE THREAD

**Issue by Castaglia** [Castaglia/proftpd-mod_vroot#2]
When mod_vroot is enabled for a session, the paths of files uploaded/downloaded that are logged to a TransferLog file are different than when mod_vroot is _not_ used for a session.

For transparency/consistency, the TransferLog entries generated for a file upload/download should be the same regardless of whether mod_vroot is used for that transfer or not.

**Comment by ws0w** [comment]
I believe I have a fix for this. I forked this repository, put my fix there and created a pull request. Basically, my fix is to add these lines to vroot_cmdtab:

```
  { CMD,                C_APPE, G_NONE, vroot_log_retr, FALSE, FALSE },
  { CMD,                C_RETR, G_NONE, vroot_log_retr, FALSE, FALSE },
  { CMD,                C_STOR, G_NONE, vroot_log_stor, FALSE, FALSE },

```
I have not found any problems with this. It seems that POST_CMD and POST_CMD_ERR processing are too late to fix the log entries.

**Comment by ws0w** [comment]
Sorry, should have been:

```
  { CMD,                C_APPE, G_NONE, vroot_log_stor, FALSE, FALSE },
  { CMD,                C_RETR, G_NONE, vroot_log_retr, FALSE, FALSE },
  { CMD,                C_STOR, G_NONE, vroot_log_stor, FALSE, FALSE },

```

**Comment by Castaglia** [comment]
Fixed in master via https://github.com/Castaglia/proftpd-mod_vroot/commit/6a64e97441ba0a04d5aa53f2ce25784ff510c0b5.
