### ISSUE TITLE
LogFormat %f handling for SFTP paths with mod_vroot

### ISSUE THREAD

**Issue by jpfinger** [Castaglia/proftpd-mod_vroot#20]
After updating from 1.3.5d to 1.3.6c, mod_vroot translates %f and %F to the same (relative to chroot) path.  Previously, %f translated to the absolute path, outside of the chroot.

See [Proftpd Issue 862](https://github.com/proftpd/proftpd/issues/862) for more detail.

**Comment by Castaglia** [comment]
Interestingly, this logging behavior does _not_ appear to happen when using ProFTPD 1.3.7rc2.

**Comment by Castaglia** [comment]
Looks like https://github.com/proftpd/proftpd/commit/50d5a49046922f51fc7ac60b7ebb9a8b3273137e is the commit which fixed this; I will need to backport this to the 1.3.6 branch.  So this is an issue in `mod_sftp`, not `mod_vroot`.

**Comment by Castaglia** [comment]
This should now be fixed in the 1.3.6 branch; see https://github.com/proftpd/proftpd/commit/15c90fd1585740665b0a7287a89685f288b7df80.
