### ISSUE TITLE
mod_vroot and proftpd 1.3.6c

### ISSUE THREAD

**Issue by Maliuta** [Castaglia/proftpd-mod_vroot#21]
While the module compiles and installs properly proftpd version 1.3.6c refuses to load ```
it:
# service proftpd check-config
2020-02-24 00:57:45,424 kiev proftpd[3471336]: mod_dso/0.5: unable to load 'mod_vroot.c'; check to see if '/usr/lib/proftpd/mod_vroot.la' exists
2020-02-24 00:57:45,424 kiev proftpd[3471336]: fatal: LoadModule: error loading module 'mod_vroot.c': No such file or directory on line 93 of '/etc/proftpd/modules.conf'
2020-02-24 00:57:45,424 kiev proftpd[3471336]: warning: unable to include '/etc/proftpd/modules.conf': Operation not permitted
ProFTPD configuration OK
```

**Comment by pghmcfc** [comment]
Works for me:
```
# proftpd --version
ProFTPD Version 1.3.6c
# ftpdctl -v lsmod
ftpdctl: adding "lsmod" to reqargv
ftpdctl: contacting server using '/run/proftpd/proftpd.sock'
ftpdctl: sending control request
ftpdctl: receiving control response
ftpdctl: Loaded Modules:
ftpdctl:   mod_core.c
ftpdctl:   mod_xfer.c
ftpdctl:   mod_rlimit.c
ftpdctl:   mod_auth_unix.c
ftpdctl:   mod_auth_file.c
ftpdctl:   mod_auth.c
ftpdctl:   mod_ls.c
ftpdctl:   mod_log.c
ftpdctl:   mod_site.c
ftpdctl:   mod_delay.c
ftpdctl:   mod_facts.c
ftpdctl:   mod_dso.c
ftpdctl:   mod_ident.c
ftpdctl:   mod_readme.c
ftpdctl:   mod_auth_pam.c
ftpdctl:   mod_tls.c
ftpdctl:   mod_memcache.c
ftpdctl:   mod_cap.c
ftpdctl:   mod_ctrls.c
ftpdctl:   mod_lang.c
ftpdctl:   mod_ctrls_admin.c
ftpdctl:   mod_vroot.c
ftpdctl:   mod_ban.c
```

**Comment by Castaglia** [comment]
@Maliuta Can you provide the exact commands you used, for compiling and installing `mod_vroot`?

**Comment by POSJensWegener** [comment]
Hi, i get the same message with official ubuntu 20.04 packages:

proftpd -V
Compile-time Settings:
  Version: 1.3.6c (maint)
  Platform: LINUX [Linux 5.4.0-31-generic x86_64]
  Built: Thu Feb 27 2020 19:34:56 UTC
  Built With:
    configure  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--with-includes=/usr/include/postgresql:/usr/include/mysql' '--mandir=/usr/share/man' '--sysconfdir=/etc/proftpd' '--localstatedir=/run' '--libexecdir=/usr/lib/proftpd' '--enable-sendfile' '--enable-facl' '--enable-dso' '--enable-autoshadow' '--enable-ctrls' '--enable-ipv6' '--enable-nls' '--enable-memcache' '--with-lastlog=/var/log/lastlog' '--enable-pcre' '--disable-strip' '--enable-redis' '--build' 'x86_64-linux-gnu' '--with-shared=mod_unique_id:mod_site_misc:mod_load:mod_ban:mod_quotatab:mod_sql:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_sql_odbc:mod_dynmasq:mod_quotatab_sql:mod_ldap:mod_quotatab_ldap:mod_ratio:mod_tls:mod_rewrite:mod_radius:mod_wrap:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_quotatab_file:mod_quotatab_radius:mod_facl:mod_ctrls_admin:mod_copy:mod_deflate:mod_ifversion:mod_geoip:mod_exec:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_shaper:mod_sql_passwd:mod_ifsession:mod_auth_otp:mod_tls_redis:mod_wrap2_redis:mod_redis:mod_memcache:mod_tls_memcache:mod_readme:mod_snmp' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-oI4YZ3/proftpd-dfsg-1.3.6c=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-oI4YZ3/proftpd-dfsg-1.3.6c=. -fstack-protector-strong -Wformat -Werror=format-security'

  CFLAGS: -g2 -g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-oI4YZ3/proftpd-dfsg-1.3.6c=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -fno-omit-frame-pointer -Werror=implicit-function-declaration
  LDFLAGS: -L$(top_srcdir)/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic  -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu
  LIBS: -lacl  -lpcreposix -lpcre -lssl -lcrypto -lcap  -lpam -lsupp -lattr -lnsl -lresolv -lresolv -lcrypt -ldl -lhiredis -lmemcachedutil -lmemcached  -pthread

  Files:
    Configuration File:
      /etc/proftpd/proftpd.conf
    Pid File:
      /run/proftpd.pid
    Scoreboard File:
      /run/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/lib/proftpd

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    + Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    + Lastlog support
    + Memcache support
    + ncursesw support
    + NLS support
    + Redis support
    - Sodium support
    + OpenSSL support
    + PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

bug-report at : https://bugs.launchpad.net/ubuntu/+source/proftpd-mod-vroot/+bug/1880683

**Comment by pghmcfc** [comment]
I don't see `mod_vroot` in the `--with-shared` list there, which might explain why it can't be found.

Also, `mod_ifsession` isn't the last module in the list, which it probably should be.

**Comment by POSJensWegener** [comment]
Hi,

in modules.conf, mod_ifsession is tha last one.  i use the official debian packages.

**Comment by hpreusse** [comment]
If you use Debian / Ubuntu you probably got hit by [this bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=951916). Sorry this was my fault and should be been soved in latest upload of mod_vroot. Thanks!

**Comment by Castaglia** [comment]
@Maliuta Can you confirm that using the latest, newest Debian packages addresses this issue?

**Comment by Castaglia** [comment]
No further contact with reporter; I'm assuming this issue has been fixed.
