### ISSUE TITLE
VRootAlias directive doesn't work when using SFTP publickey auth

### ISSUE THREAD

**Issue by kkatpcc** [Castaglia/proftpd-mod_vroot#30]
### Setup
- OS: Oracle Linux 8 (based on RHEL 8.4)
- ProFTPD version: 1.3.6e with mod_vroot 0.9.5 (proftpd-1.3.6e-2.el8.x86_64 from standard repo via dnf install)
- Protocol: SFTP only
- SFTPAuthMethods password publickey (doesn't matter which order, or if publickey only)

### Problem
When using SFTP publickey authentication, the VRootAlias directive fails to work. The alias directories are missing in the SFTP list and the vroot log file shows the following types of errors: "error stashing VRootAlias '/some/alias/path': Invalid argument"

When using SFTP password authentication, the VRootAlias directive works fine. The alias directories are present in the SFTP list and vroot log file shows the following types of successes: "aliased '/some/alias/path' to real path '/some/real/path'"

I've traced the problem as far back as [vroot_post_pass_err()](https://github.com/Castaglia/proftpd-mod_vroot/blob/v0.9.5/mod_vroot.c#L427), which seems to be called because of a blank or omitted password during SFTP publickey auth. That, in turn, calls [vroot_alias_free()](https://github.com/Castaglia/proftpd-mod_vroot/blob/v0.9.5/alias.c#L109) early on, thus nullifying alias_pool and alias_tab. As a result, any attempt to call [vroot_alias_add()](https://github.com/Castaglia/proftpd-mod_vroot/blob/v0.9.5/alias.c#L79) afterwards results in the "error stashing" problem because [pr_table_add()](https://github.com/proftpd/proftpd/blob/v1.3.6e/src/table.c#L796) does a sanity check for null on the tab/pool and fails out.

### Extended Logs
Using FileZilla FTP client with publickey auth:
```
"KEXINIT" - -
"ECDH_INIT" - -
"NEWKEYS" - -
"SERVICE_REQUEST" - -
"USER sftp-user" 331 -
"USERAUTH_REQUEST sftp-user none" - -
"USER sftp-user" 331 -
"PASS (hidden)" 530 -
"USERAUTH_REQUEST sftp-user publickey" - -
"USER sftp-user" 331 -
"PASS (hidden)" 230 -
"USERAUTH_REQUEST sftp-user publickey" - -
"CHANNEL_OPEN session" - -
"CHANNEL_REQUEST simple@putty.projects.tartarus.org" - -
"CHANNEL_REQUEST subsystem" - -
"INIT 3" - -
"REALPATH ." - -
"REALPATH /" - -
"OPENDIR /" - 0
"MLSD /" - 0
"CLOSE b9b35e1c348ff14d" 0 0
"REALPATH /." - -
"OPENDIR /" - 0
"READDIR 0f95dc121946d508" - 309
"READDIR 0f95dc121946d508" 1 309
"READDIR 0f95dc121946d508" 1 309
"READDIR 0f95dc121946d508" 1 309
"READDIR 0f95dc121946d508" 1 309
"MLSD /" - 309
"CLOSE 0f95dc121946d508" 0 0
```
Command line sftp client (no special options, defaults to publickey auth)
```
"KEXINIT" - -
"ECDH_INIT" - -
"NEWKEYS" - -
"SERVICE_REQUEST" - -
"USER sftp-user" 331 -
"USERAUTH_REQUEST sftp-user none" - -
"USER sftp-user" 331 -
"PASS (hidden)" 530 -
"USERAUTH_REQUEST sftp-user publickey" - -
"USER sftp-user" 331 -
"PASS (hidden)" 230 -
"USERAUTH_REQUEST sftp-user publickey" - -
"CHANNEL_OPEN session" - -
"CHANNEL_REQUEST env" - -
"CHANNEL_REQUEST subsystem" - -
"INIT 3" - -
"REALPATH ." - -
"OPENDIR /" - 0
"READDIR d9b8f0512a65af77" - 309
"READDIR d9b8f0512a65af77" 1 309
"MLSD /" - 309
"CLOSE d9b8f0512a65af77" 0 0
```
Command line sftp client when forcing password (-o PreferredAuthentications=password -o PubkeyAuthentication=no)
```
"KEXINIT" - -
"ECDH_INIT" - -
"NEWKEYS" - -
"SERVICE_REQUEST" - -
"USER sftp-user" 331 -
"USERAUTH_REQUEST sftp-user none" - -
"USER sftp-user" 331 -
"PASS (hidden)" 230 -
"USERAUTH_REQUEST sftp-user password" - -
"CHANNEL_OPEN session" - -
"CHANNEL_REQUEST env" - -
"CHANNEL_REQUEST subsystem" - -
"INIT 3" - -
"REALPATH ." - -
"OPENDIR /" - 0
"READDIR a516486ea3088c88" - 1051
"READDIR a516486ea3088c88" 1 1051
"MLSD /" - 1051
"CLOSE a516486ea3088c88" 0 0
```

As you can see, READDIR is returning more content on the last set of logs because VRootAlias is properly working there when using/forcing password auth.

### Working counter-example with older version

The above ProFTPd configuration is identical to an older server running Oracle Linux 7 with ProFTPD 1.3.5e containing mod_vroot 0.9.2 from the standard repo. We have no such VRootAlias problems on said older server.

Here is what a command line sftp publickey connection looks like on that older server:
```
"KEXINIT" - -
"ECDH_INIT" - -
"NEWKEYS" - -
"SERVICE_REQUEST" - -
"USER sftp-user" 331 -
"USERAUTH_REQUEST" - -
"USER sftp-user" 331 -
"PASS (hidden)" 530 -
"USERAUTH_REQUEST" - -
"USER sftp-user" 331 -
"PASS (hidden)" 230 -
"USERAUTH_REQUEST" - -
"CHANNEL_OPEN" - -
"CHANNEL_REQUEST" - -
"CHANNEL_REQUEST" - -
"INIT 3" - -
"REALPATH ." - -
"OPENDIR /" - 0
"READDIR 8d84a1746f80597f" - 1051
"READDIR 8d84a1746f80597f" 1 1051
"MLSD /" - 1051
"CLOSE 8d84a1746f80597f" 0 0
```
Given how identical the above looks between ProFTPD versions, it seems like a subtle bug/regression may have been introduced between mod_vroot 0.9.2 and mod_vroot 0.9.5.

**Comment by Castaglia** [comment]
Excellent diagnosis; thanks for digging into this.  I'll work on a regression test, to reproduce this issue locally -- especially useful, now that the module regression tests will be run on all future PRs, as part of the CI workflow.

**Comment by Castaglia** [comment]
Actually, this behavior _may_ be fixed by [this commit](https://github.com/Castaglia/proftpd-mod_vroot/commit/9ac8c61048ec33579cf71fd988077b9f5b5dfd50).  Could you verify, while I still reproduce this locally?

**Comment by kkatpcc** [comment]
I've verified that [said commit](https://github.com/Castaglia/proftpd-mod_vroot/commit/9ac8c61048ec33579cf71fd988077b9f5b5dfd50) does **not** resolve the issue.

Manually adding `vroot_alias_init(session.pool);` after `vroot_alias_free();` to said commit still resolves it as before.

**Comment by kkatpcc** [comment]
I am using the stock config from the [OL8 repo](https://yum.oracle.com/repo/OracleLinux/OL8/developer/EPEL/x86_64/getPackageSource/proftpd-1.3.6e-2.el8.src.rpm) (which splits out across different files) with the following relevant customizations:
- Ensuring mod_sftp is loaded by uncommenting relevant include line; mod_vroot is already included by default
- SFTPEngine on
- SFTPOptions InsecureHostKeyPerms IgnoreSFTPUploadPerms
- SFTPHostKey /path/to/your/rsa-key
- SFTPHostKey /path/to/your/ecdsa-key
- SFTPAuthMethods password publickey
- SFTPAuthorizedUserKeys /some/relevant/path/setting
- VRootAlias /some/real/path ~/relative-alias-path

**Comment by Castaglia** [comment]
Interesting; I don't see this behavior, using the latest `mod_vroot`, with the latest ProFTPD 1.3.8rc2 release, but I _do_ see it with ProFTPD 1.3.6.  I'll check using 1.3.7c as well.  But this suggests that the fix may need to be dependent on the core ProFTPD version, depending on just what the differences are.

**Comment by Castaglia** [comment]
https://github.com/Castaglia/proftpd-mod_vroot/pull/31 seemed to fix things locally, using ProFTPD 1.3.6, ProFTPD 1.3.7, and ProFTPD 1.3.8, for me.  Care to see if it addresses the issue for you as well?

**Comment by kkatpcc** [comment]
Confirmed. #31 addresses the issue for me.

**Comment by Castaglia** [comment]
This should now be fixed in master.
